baseURL: https://luk3ya0.github.io/
languageCode: en-us 
title: Luke's Code Life
theme: Eclectic 
author: 
  email: "oneTOinf@163.com" 
  name: "Luke Yao" 
  location: Shen Zhen

menu:
  main: 
    - identifier: about 
      name: About 
      url: /about 
      weight: 100 
    - identifier: contact 
      name: Contact 
      url: /contact 
      weight: 200 
params: 
  color: "#4f46e5"
  footer:
  - title: About
    content: >
      Nothing.

  - title: Recent Blog Posts
    recents: blog
    recentCount: 7

  - title: Contact Us
    contact: true
